### ISSUE TITLE
with jQueryUI animation broken

### ISSUE THREAD

**Issue by mgrulich** [fredleblanc/roundabout#48]
Hi,

i´m allready using jQuery UI in my Project and i wondered why roundabout animations are not correctly.
There is a wild animation :-)

I identified the problem to jQueryUI, only when i have remove jQueryUI from my Project roundabout animates correct.

Without the Effects modules it will working correctly.

Is there a solution?

Thanx Martin

**Comment by snichini** [comment]
same here with latest ui / jquery / roundabout

**Comment by fredleblanc** [comment]
This is due to jQuery easing, which has just been fixed in v2.4.2.

**Comment by isclanem** [comment]
i have the same problems, my project contain:

jquery ui 1.9.1
jquery 1.8.2

and jquery.roundabout.js 2.4.2

the problem is that roundabout animates effect is not working when i have "jquery ui 1.9.1", "jquery 1.8.2" and "jquery.roundabout.js 2.4.2"

the roundabout animates effect working correct when remove "jquery ui 1.9.1"

please need help

**Comment by el-banan** [comment]
Same here, animation breaks when using easings from http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js
Maybe jQ UI from Google's CDN has broken easings?

**Comment by k3llyb** [comment]
I am having an issue that the roundabout expands way outside of the wrapper and container.  It doesn't do this all the time, usually when someone refreshes the page and most often in chrome.  I have done everything I can think of to tweak and I still get this issue

Thanks in advance for any help
![Screen Shot](https://f.cloud.github.com/assets/3578731/150704/427ed0a6-755a-11e2-8d05-c36214135d8d.png)
.
